services:

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka

    ports:
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_DELETE_TOPIC_ENABLE: "true"

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk


  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark

    container_name: spark

    ports:
      - "4040:4040"

    volumes:
      - ./:/app

    command: >
      tail -f /dev/null

    depends_on:
      - kafka

  redis:
    image: redis:7-alpine

    container_name: redis

    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: frauduser
      POSTGRES_PASSWORD: fraudpass
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"